package com.kaustuv.poc.ws.service.greetings;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-04-05T13:33:04.779+05:30
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "OrganizationService", 
                  wsdlLocation = "http://poc.kaustuv.com/ws/service/greetings?wsdl",
                  targetNamespace = "http://poc.kaustuv.com/ws/service/greetings") 
public class OrganizationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://poc.kaustuv.com/ws/service/greetings", "OrganizationService");
    public final static QName JmsEndpointPort = new QName("http://poc.kaustuv.com/ws/service/greetings", "JmsEndpointPort");
    public final static QName HttpEndpointPort = new QName("http://poc.kaustuv.com/ws/service/greetings", "HttpEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://poc.kaustuv.com/ws/service/greetings?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrganizationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://poc.kaustuv.com/ws/service/greetings?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrganizationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrganizationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganizationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Organization
     */
    @WebEndpoint(name = "JmsEndpointPort")
    public Organization getJmsEndpointPort() {
        return super.getPort(JmsEndpointPort, Organization.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Organization
     */
    @WebEndpoint(name = "JmsEndpointPort")
    public Organization getJmsEndpointPort(WebServiceFeature... features) {
        return super.getPort(JmsEndpointPort, Organization.class, features);
    }
    /**
     *
     * @return
     *     returns Organization
     */
    @WebEndpoint(name = "HttpEndpointPort")
    public Organization getHttpEndpointPort() {
        return super.getPort(HttpEndpointPort, Organization.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Organization
     */
    @WebEndpoint(name = "HttpEndpointPort")
    public Organization getHttpEndpointPort(WebServiceFeature... features) {
        return super.getPort(HttpEndpointPort, Organization.class, features);
    }

}
