package com.kaustuv.poc.ws.service.greetings;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-04-05T13:33:04.772+05:30
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://poc.kaustuv.com/ws/service/greetings", name = "Organization")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Organization {

    @WebResult(name = "return", targetNamespace = "http://poc.kaustuv.com/ws/service/greetings", partName = "return")
    @WebMethod
    public java.lang.String getContactInfo(
        @WebParam(partName = "name", name = "name")
        java.lang.String name
    );
}
