/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.kaustuv.poc.ws.service.greetings;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-04-05T13:33:04.759+05:30
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(serviceName = "OrganizationService", portName = "JmsEndpointPort", targetNamespace = "http://poc.kaustuv.com/ws/service/greetings", wsdlLocation = "WEB-INF/wsdl/Sample.wsdl", endpointInterface = "com.kaustuv.poc.ws.service.greetings.Organization")
public class OrganizationJmsImpl implements Organization {

  private static final Logger LOG = Logger.getLogger(OrganizationImpl.class.getName());

  /* (non-Javadoc)
   * @see com.kaustuv.poc.ws.service.greetings.Organization#getContactInfo(java.lang.String  name )*
   */
  public java.lang.String getContactInfo(java.lang.String name) {
    LOG.info("Executing operation getContactInfo");
    java.lang.String _return = "JmsEndPoint Response" + name + "Is not active now your call is register to queue";
    return _return;
  }

}
