
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.kaustuv.poc.ws.service.greetings;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-04-05T13:33:04.633+05:30
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrganizationService",
                      portName = "HttpEndpointPort",
                      targetNamespace = "http://poc.kaustuv.com/ws/service/greetings",
                      wsdlLocation = "WEB-INF/wsdl/Sample.wsdl",
                      endpointInterface = "com.kaustuv.poc.ws.service.greetings.Organization")

public class OrganizationImpl implements Organization {

    private static final Logger LOG = Logger.getLogger(OrganizationImpl.class.getName());

    /* (non-Javadoc)
     * @see com.kaustuv.poc.ws.service.greetings.Organization#getContactInfo(java.lang.String  name )*
     */
    public java.lang.String getContactInfo(java.lang.String name) { 
        LOG.info("Executing operation getContactInfo");
        try {
            java.lang.String _return = "Http End point result" + name;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
